Repository wecode-bootcamp-korea/32-2nd-GGSD-frontend, pull requests merged in 2022-05, with the labels that each got.

#4 [32기 이하영]card 컴포넌트화
  package-lock.json
  src/assets/wecodebanner.png
  src/components/Card/Card.js
  src/components/Card/cardData.js
Labels: Status: Accepted

#2 [32기 이희준] Button Components 작업완료
  src/components/Button/Buttons.js
Labels: Status: Accepted

#5 [32기 이희준] Modify: 리뷰반영
  src/components/Button/Buttons.js
Labels: Status: 리뷰 요청

#10 [32기 이하영]Add: join modal 레이아웃 구현완성
  src/components/JoinModal/JoinModal.js
Labels: Status: 리뷰 요청

#7 [32기 이하영] Add: 메인페이지 레이아웃 구현 완료
  package-lock.json
  package.json
  public/images/001.jpg
  public/images/002.jpg
  public/images/003.jpg
  public/images/004.jpg
  public/images/readme.md
  public/images/wecodebanner.png
  src/components/Card/Card.js
  src/components/JoinModal/JoinModal.js
  src/pages/Main/Main.js
  src/pages/Main/ProjectCarousel.js
  src/pages/Main/carouselData.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#8 [32기 최승이] 프로젝트 생성 페이지
  .vscode/launch.json
  package-lock.json
  package.json
  public/images/thumbnail_default.jpg
  src/pages/CreateProject/CreateProject.js
  src/pages/CreateProject/CreateProject.style.js
  src/pages/CreateProject/index.js
  src/styles/Theme.js
Labels: Status: Rebase 요청

#13 Add:fetch 상위컴포넌트로 옮김
  src/pages/Main/Main.js
  src/pages/Main/ProjectCarousel.js
Labels: Status: 리뷰 요청

#9 [32기 이하영] initial setting modal 기능 구현 완료
  src/Router.js
  src/components/AdditionalInfo/AdditionalInfo.js
  src/components/Initial/Initial.js
Labels: Status: 리뷰 요청

#6 ADD [32기 정덕우]Footer 작업완료
  public/images/logo.png
  src/components/Footer/Footer.js
Labels: Status: 수정 요청, Status: 추가 기능 구현중

#15 [32기 이희준] 리스트페이지 리팩토링 작업 완료 및 수정작업 완료
  src/components/Card/Card.js
  src/pages/List/List.js
Labels: Status: 리뷰 요청

#11 [32기 정덕우] 네브 구현
  .gitignore
  public/images/kakaologin.png
  src/Router.js
  src/components/AdditionalInfo/AdditionalInfo.js
  src/components/CustomHook/useLockBodyScroll.js
  src/components/CustomHook/useToggle.js
  src/components/Footer/Footer.js
  src/components/Nav/InitialModal.js
  src/components/Nav/LoginModal.js
  src/components/Nav/Nav.js
  src/components/Nav/ProfileModal.js
  src/components/Nav/SearchCard.js
  src/config.js
  src/pages/Login/KakaoLogin.js
  src/pages/Login/Login.js
Labels: Status: 리뷰 요청

#16 [32기 정덕우]마이페이지 완료
  src/components/Button/Buttons.js
  src/pages/Main/Main.js
  src/pages/MyPage/GitHubModal.js
  src/pages/MyPage/GitHubWrapper.js
  src/pages/MyPage/InfoCard.js
  src/pages/MyPage/Mypage.js
  src/pages/MyPage/PortfolioModal.js
  src/pages/MyPage/PortfolioWrapper.js
  src/pages/MyPage/StackModal.js
  src/pages/MyPage/StackWrapper.js
Labels: Status: 리뷰 요청

#17 [32기 이하영]Add: 메인페이지 기능구현 완성
  src/components/AdditionalInfo/AdditionalInfo.js
  src/components/Card/Card.js
  src/components/Card/cardData.js
  src/components/Footer/Footer.js
  src/pages/Main/Main.js
  src/pages/Main/ProjectCarousel.js
Labels: Status: Accepted

#12 [32기 최승이] 디테일페이지 구현
  public/images/filedown.svg
  src/Router.js
  src/components/AdditionalInfo/AdditionalInfo.js
  src/components/JoinModal/JoinModal.js
  src/config.js
  src/pages/CreateProject/CreateProject.js
  src/pages/CreateProject/CreateProject.style.js
  src/pages/Detail/Detail.js
  src/pages/Login/KakaoLogin.js
Labels: Status: Accepted
